/**
 * The two geocode tables, fetched once and shared.
 *
 * Module singletons rather than context state: they are immutable reference data
 * generated by `pnpm geocode:build` / `geocode:clubs`, both maps want them, and
 * fetching them twice would pull 400KB twice.
 *
 * Holds state and actions only, no `$effect` — the component that needs the data
 * calls `load()`.
 */
export interface JsonResource<T> {
	readonly data: T | null;
	readonly loading: boolean;
	readonly error: string | null;
}

function jsonResource<T>(url: string) {
	let data = $state<T | null>(null);
	let loading = $state(false);
	let error = $state<string | null>(null);
	let started = false;

	return {
		get data() {
			return data;
		},
		get loading() {
			return loading;
		},
		get error() {
			return error;
		},
		/** Fetch once. Safe to call from every component that needs it. */
		async load(): Promise<void> {
			if (started) return;
			started = true;
			loading = true;
			error = null;
			try {
				const response = await fetch(url);
				if (!response.ok) throw new Error(`${response.status} ${response.statusText}`);
				data = (await response.json()) as T;
			} catch (err) {
				// Allow a retry — a failed geocode table means an empty map, not a
				// permanently broken one.
				started = false;
				error = err instanceof Error ? err.message : `Failed to load ${url}`;
			} finally {
				loading = false;
			}
		}
	};
}

export const cityGeocodes =
	jsonResource<import('./geocodeLoader').GeocodeData>('/data/geocodes.json');
export const clubGeocodes = jsonResource<import('./geocodeLoader').ClubGeocodeData>(
	'/data/club-geocodes.json'
);
